### ISSUE TITLE
I am getting this error PermissionError: [Errno 13] Permission denied: '/home/projects' 

### ISSUE THREAD

**Issue by hadysysdev** [HPI-Information-Systems/TimeEval#83]
I followed the [ how to use custom_data with TimeEval guide](https://timeeval.readthedocs.io/en/latest/user/integrate-dataset.html), but somehow i am not able to do this, i keep getting the same error, tried on a window WSL, and on a Linux machine.  I believe this has something to do with the HPI_CLUSTER.akita_dataset_paths[HPI_CLUSTER.BENCHMARK], since am trying to use custom_dataset. 

```Directory /home/projects/akita/data/benchmark-data/data-processed does not exist, creating it!
Traceback (most recent call last):
  File "/home/ubuntu/miniconda3/envs/timeeval/lib/python3.8/pathlib.py", line 1288, in mkdir
    self._accessor.mkdir(self, mode)
FileNotFoundError: [Errno 2] No such file or directory: '/home/projects/akita/data/benchmark-data/data-processed'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/home/ubuntu/miniconda3/envs/timeeval/lib/python3.8/pathlib.py", line 1288, in mkdir
    self._accessor.mkdir(self, mode)
FileNotFoundError: [Errno 2] No such file or directory: '/home/projects/akita/data/benchmark-data'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/home/ubuntu/miniconda3/envs/timeeval/lib/python3.8/pathlib.py", line 1288, in mkdir
    self._accessor.mkdir(self, mode)
FileNotFoundError: [Errno 2] No such file or directory: '/home/projects/akita/data'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/home/ubuntu/miniconda3/envs/timeeval/lib/python3.8/pathlib.py", line 1288, in mkdir
    self._accessor.mkdir(self, mode)
FileNotFoundError: [Errno 2] No such file or directory: '/home/projects/akita'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "main.py", line 57, in <module>
    main()
  File "main.py", line 19, in main
    dm = DatasetManager(HPI_CLUSTER.akita_dataset_paths[HPI_CLUSTER.BENCHMARK], custom_datasets_file=custom_dataset)
  File "/home/ubuntu/miniconda3/envs/timeeval/lib/python3.8/site-packages/timeeval/datasets/dataset_manager.py", line 80, in __init__
    df = self._create_index_file(self._filepath)
  File "/home/ubuntu/miniconda3/envs/timeeval/lib/python3.8/site-packages/timeeval/datasets/datasets.py", line 70, in _create_index_file
    dataset_dir.mkdir(parents=True)
  File "/home/ubuntu/miniconda3/envs/timeeval/lib/python3.8/pathlib.py", line 1292, in mkdir
    self.parent.mkdir(parents=True, exist_ok=True)
  File "/home/ubuntu/miniconda3/envs/timeeval/lib/python3.8/pathlib.py", line 1292, in mkdir
    self.parent.mkdir(parents=True, exist_ok=True)
  File "/home/ubuntu/miniconda3/envs/timeeval/lib/python3.8/pathlib.py", line 1292, in mkdir
    self.parent.mkdir(parents=True, exist_ok=True)
  [Previous line repeated 1 more time]
  File "/home/ubuntu/miniconda3/envs/timeeval/lib/python3.8/pathlib.py", line 1288, in mkdir
    self._accessor.mkdir(self, mode)
PermissionError: [Errno 13] Permission denied: '/home/projects'```

**Comment by CodeLionX** [comment]
Assuming the issue is completed. If there are still open questions, please re-open the issue.
